
services:
  go-server:
    container_name: "k6_go_serve"
    build: ./go-server
    tty: true
    ports:
      - "1234:1234"

  k6:
    container_name: "k6_run"
    image: grafana/k6:2.1.0
    network_mode: host
    environment:
      - K6_WEB_DASHBOARD=true
    volumes:
      - ./k6:/scripts
    entrypoint: ["sleep", "infinity"]
    tty: true